#! /bin/sh
### BEGIN INIT INFO
# Provides: iop-loc
# Required-Start: $all
# Required-Stop: $all
# Default-Start: 3 4 5
# Default-Stop: 0 1 2 6
# Short-Description: IoP LOC server
# Description: This file starts and stops IoP LOC server
# 
### END INIT INFO


case "$1" in
 start)
   su {USER} -c "\"{BIN}\" --configfile \"{CFG}\" &"
   ;;
 stop)
   killall -INT iop-locnetd
   sleep 5
   ;;
 restart)
   killall -INT iop-locnetd
   sleep 20
   su {USER} -c "\"{BIN}\" --configfile \"{CFG}\" &"
   ;;
 *)
   echo "Usage: iop-loc {start|stop|restart}" >&2
   exit 3
   ;;
esac